# Generated by Django 5.0.6 on 2024-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='问题')),
                ('answer', models.TextField(help_text='答案')),
                ('ip', models.CharField(help_text='ip', max_length=255)),
                ('create_time', models.CharField(help_text='创建时间', max_length=255)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
