# Generated by Django 5.0.6 on 2024-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarNumberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(help_text='组名')),
                ('car_number', models.TextField(help_text='车牌号')),
                ('create_time', models.TextField(help_text='创建时间')),
            ],
            options={
                'db_table': 'car_numbers_group',
            },
        ),
    ]
